controller_list:
  - name: fake_kuka_structure_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
initial:  # Define initial robot poses per group
#  - group: kuka_structure
#    pose: home

  []