# Configuration file for DELTA drive
vendor_id: 0x000001dd
product_id: 0x10305070
assign_activate: 0x0300  # DC Synch register
auto_fault_reset: true  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"
auto_state_transitions: false
sdo:  # sdo data to be transferred at drive startup
  - {index: 0x60C2, sub_index: 1, type: int8, value: 1} # Set interpolation time for cyclic modes to 10 ms
  - {index: 0x60C2, sub_index: 2, type: int8, value: -3} # Set base 10-3s
  - {index: 0x6083, sub_index: 0, type: uint32, value: 200} # Set base 10-3s
  - {index: 0x6084, sub_index: 0, type: uint32, value: 200} # Set base 10-3s
  - {index: 0x6098, sub_index: 0, type: int8, value: 1} # Homing method
  - {index: 0x6099, sub_index: 1, type: uint32, value: 600} # Homing speed
  - {index: 0x6099, sub_index: 2, type: uint32, value: 40} # Homing speed
  - {index: 0x6081, sub_index: 0, type: uint32, value: 200} # Profile velocity
rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1601
    channels:
      - {index: 0x6040, sub_index: 0, type: uint16, default: 0, command_interface: ctrl_word}  # Control word
      - {index: 0x607a, sub_index: 0, type: int32, command_interface: position, default: .nan, factor: 3.75e07}  # Target position [m]
      - {index: 0x60FF, sub_index: 0, type: int32, command_interface: velocity, default: .nan, factor: 2.25e04}  # Target velocity [m/s]'
      - {index: 0x6071, sub_index: 0, type: int16, default: 0, factor: 1.0471e-04}  # Target torque [Nm]
      - {index: 0x6060, sub_index: 0, type: int8,  default: 6, command_interface: moo}  # Mode of operation
tpdo:  # TxPDO = transmit PDO Mapping
  - index: 0x1a01
    channels:
      - {index: 0x6041, sub_index: 0, type: uint16, state_interface: status_word}  # Status word
      - {index: 0x6064, sub_index: 0, type: int32,  state_interface: position, factor: 2.667e-08}  # Position actual value [m]
      - {index: 0x606c, sub_index: 0, type: int32,  state_interface: velocity, factor: 4.4445e-05}  # Velocity actual value [m/s]
      - {index: 0x6077, sub_index: 0, type: int16,  state_interface: effort, factor: 9550}  # Torque actual value [Nm]
      - {index: 0x6061, sub_index: 0, type: int8,   state_interface: moo_display}  # Mode of operation display
      # - {index: 0x607a, sub_index: 0, type: int32,  state_interface: target_position, factor: 2.667e-08}  # Target position [m]
