# Configuration file for Beckhoff EL3008
vendor_id: 0x00000002
product_id: 0x0bc03052
tpdo:  # TxPDO
  - index: 0x1a00
    channels:
    - {index: 0x6000, sub_index: 11, type: int16, state_interface: analog_input.1}
  - index: 0x1a02
    channels:
    - {index: 0x6010, sub_index: 11, type: int16, state_interface: analog_input.2}

sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~,    watchdog: disable}
  - {index: 1, type: input,  pdo: ~,    watchdog: disable}
  - {index: 2, type: output, pdo: ~,    watchdog: disable}
  - {index: 3, type: input,  pdo: tpdo, watchdog: disable}
