# Configuration file for Beckhoff EL3008
vendor_id: 0x00000002
product_id: 0x0bc03052
tpdo:  # TxPDO
- index: 0x1a00
  channels:
  - {index: 0x0000, sub_index: 00, type: bool}  
  - {index: 0x0000, sub_index: 00, type: bit6}  
  - {index: 0x6000, sub_index: 01, type: bool} 
  - {index: 0x6000, sub_index: 02, type: bool}
  - {index: 0x6000, sub_index: 03, type: bit2}
  - {index: 0x6000, sub_index: 05, type: bit2}
  - {index: 0x6000, sub_index: 07, type: bool}
  - {index: 0x6000, sub_index: 15, type: bool}
  - {index: 0x6000, sub_index: 10, type: bool}
  - {index: 0x6000, sub_index: 11, type: int16, state_interface: sensor_channel_0}
- index: 0x1a02
  channels:
  - {index: 0x0000, sub_index: 00, type: bool}  
  - {index: 0x0000, sub_index: 00, type: bit6}  
  - {index: 0x6010, sub_index: 01, type: bool} 
  - {index: 0x6010, sub_index: 02, type: bool}
  - {index: 0x6010, sub_index: 03, type: bit2}
  - {index: 0x6010, sub_index: 05, type: bit2}
  - {index: 0x6010, sub_index: 07, type: bool}
  - {index: 0x6010, sub_index: 15, type: bool}
  - {index: 0x6010, sub_index: 10, type: bool}
  - {index: 0x6010, sub_index: 11, type: int16, state_interface: sensor_channel_1}
- index: 0x1a04
  channels:
  - {index: 0x0000, sub_index: 00, type: bool}  
  - {index: 0x0000, sub_index: 00, type: bit6}  
  - {index: 0x6020, sub_index: 01, type: bool} 
  - {index: 0x6020, sub_index: 02, type: bool}
  - {index: 0x6020, sub_index: 03, type: bit2}
  - {index: 0x6020, sub_index: 05, type: bit2}
  - {index: 0x6020, sub_index: 07, type: bool}
  - {index: 0x6020, sub_index: 15, type: bool}
  - {index: 0x6020, sub_index: 10, type: bool}
  - {index: 0x6020, sub_index: 11, type: int16, state_interface: sensor_channel_2}
- index: 0x1a06
  channels:
  - {index: 0x0000, sub_index: 00, type: bool}  
  - {index: 0x0000, sub_index: 00, type: bit6}  
  - {index: 0x6030, sub_index: 01, type: bool} 
  - {index: 0x6030, sub_index: 02, type: bool}
  - {index: 0x6030, sub_index: 03, type: bit2}
  - {index: 0x6030, sub_index: 05, type: bit2}
  - {index: 0x6030, sub_index: 07, type: bool}
  - {index: 0x6030, sub_index: 15, type: bool}
  - {index: 0x6030, sub_index: 10, type: bool}
  - {index: 0x6030, sub_index: 11, type: int16, state_interface: sensor_channel_3}
- index: 0x1a08
  channels:
  - {index: 0x0000, sub_index: 00, type: bool}  
  - {index: 0x0000, sub_index: 00, type: bit6}  
  - {index: 0x6040, sub_index: 01, type: bool} 
  - {index: 0x6040, sub_index: 02, type: bool}
  - {index: 0x6040, sub_index: 03, type: bit2}
  - {index: 0x6040, sub_index: 05, type: bit2}
  - {index: 0x6040, sub_index: 07, type: bool}
  - {index: 0x6040, sub_index: 15, type: bool}
  - {index: 0x6040, sub_index: 10, type: bool}
  - {index: 0x6040, sub_index: 11, type: int16, state_interface: sensor_channel_4}
- index: 0x1a0a
  channels:
  - {index: 0x0000, sub_index: 00, type: bool}  
  - {index: 0x0000, sub_index: 00, type: bit6}  
  - {index: 0x6050, sub_index: 01, type: bool} 
  - {index: 0x6050, sub_index: 02, type: bool}
  - {index: 0x6050, sub_index: 03, type: bit2}
  - {index: 0x6050, sub_index: 05, type: bit2}
  - {index: 0x6050, sub_index: 07, type: bool}
  - {index: 0x6050, sub_index: 15, type: bool}
  - {index: 0x6050, sub_index: 10, type: bool}
  - {index: 0x6050, sub_index: 11, type: int16, state_interface: sensor_channel_5}
- index: 0x1a0c
  channels:
  - {index: 0x0000, sub_index: 00, type: bool}  
  - {index: 0x0000, sub_index: 00, type: bit6}  
  - {index: 0x6060, sub_index: 01, type: bool} 
  - {index: 0x6060, sub_index: 02, type: bool}
  - {index: 0x6060, sub_index: 03, type: bit2}
  - {index: 0x6060, sub_index: 05, type: bit2}
  - {index: 0x6060, sub_index: 07, type: bool}
  - {index: 0x6060, sub_index: 15, type: bool}
  - {index: 0x6060, sub_index: 10, type: bool}
  - {index: 0x6060, sub_index: 11, type: int16, state_interface: a_input_6}
- index: 0x1a0e
  channels:
  - {index: 0x0000, sub_index: 00, type: bool}  
  - {index: 0x0000, sub_index: 00, type: bit6}  
  - {index: 0x6070, sub_index: 01, type: bool} 
  - {index: 0x6070, sub_index: 02, type: bool}
  - {index: 0x6070, sub_index: 03, type: bit2}
  - {index: 0x6070, sub_index: 05, type: bit2}
  - {index: 0x6070, sub_index: 07, type: bool}
  - {index: 0x6070, sub_index: 15, type: bool}
  - {index: 0x6070, sub_index: 10, type: bool}
  - {index: 0x6070, sub_index: 11, type: int16, state_interface: a_input_7}

sm:  # Sync Manager
  - {index: 0, type: output, pdo: rsdo, watchdog: enable}
  - {index: 1, type: input,  pdo: tsdo, watchdog: enable}
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input,  pdo: tpdo, watchdog: enable}



#tpdo:  # TxPDO
#  - index: 0x1axx
#    channels:
#    - {index: 0x6000, sub_index: 00, type: uint8} # AI Inputs     Maximum subindex                                                                            default: 0x11
#    - {index: 0x6000, sub_index: 01, type: bool}  # Underrange    Value below measuring range                                                                 default: 0x00
#    - {index: 0x6000, sub_index: 02, type: bool}  # Overrange     Measuring range exceeded                                                                    default: 0x00
#    - {index: 0x6000, sub_index: 03, type: bit2}  # Limit 1       Limit value monitoring Limit 1                                                              default: 0x00
#                                                                      # 0: not active
#                                                                      # 1: value is smaller than limit value 1
#                                                                      # 2: value is greater than limit value 1
#                                                                      # 3: value is equal to limit value 1
#    - {index: 0x6000, sub_index: 05, type: bit2}  # Limit 2       Limit value monitoring Limit 2                                                              default: 0x00
#                                                                      # 0: not active
#                                                                      # 1: value is smaller than limit value 2
#                                                                      # 2: value is greater than limit value 2
#                                                                      # 3: value is equal to limit value 2
#    - {index: 0x6000, sub_index: 07, type: bool}  # Error         The error bit is set if the data is invalid (over-range,under-range)                        default: 0x00
#    - {index: 0x6000, sub_index: 15, type: bool}  # TxPDO State   Validity of the data of the associated TxPDO (0 = valid, 1 = invalid)                       default: 0x00
#    - {index: 0x6000, sub_index: 10, type: bool}  # TxPDO Toggle  The TxPDO toggle is toggled by the slave when the data of the associated TxPDO is updated   default: 0x00
#    - {index: 0x6000, sub_index: 11, type: int16} # Value         Analog input datedefault: 0x0000
