# Configuration file for DELTA drive
vendor_id: 0x000001dd
product_id: 0x10305070
assign_activate: 0x0300  # DC Synch register
auto_fault_reset: false  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"
sdo:  # sdo data to be transferred at drive startup
  - {index: 0x60C2, sub_index: 1, type: int8, value: 1} # Set interpolation time for cyclic modes to 10 ms
  - {index: 0x60C2, sub_index: 2, type: int8, value: -3} # Set base 10-3s
rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1601
    channels:
      - {index: 0x6040, sub_index: 0, type: uint16, default: 134, state_interface: ctrl_word}  # Control word
      - {index: 0x607a, sub_index: 0, type: int32, command_interface: position, default: .nan}  # Target position
tpdo:  # TxPDO = transmit PDO Mapping
  - index: 0x1a01
    channels:
      - {index: 0x6041, sub_index: 0, type: uint16, state_interface: status_word}  # Status word
      - {index: 0x6064, sub_index: 0, type: int32, state_interface: position}  # Position actual value
