delta_utils:
  ros__parameters:
    control_word:
      controller_name: delta_controller
      command_interface: joint_1/ctrl_word
    status_word:
      controller_name: delta_controller
      state_interface: joint_1/status_word
    mode_of_operation:
      controller_name: delta_controller
      command_interface: joint_1/moo
    mode_of_operation_display:
      controller_name: delta_controller
      state_interface: joint_1/moo_display

    joint_trajectory_controller_name: joint_trajectory_controller

battery_cell_utils:
  ros__parameters:
    lubrication:
      command_controller_name: digital_io_controller
      command_interface: digital_outputs1/lubrication_command
      state_controller_name: digital_io_controller
      state_interface: digital_inputs/lubrication_state
    pneumatic_gripper:
      controller_name: digital_io_controller
      command_interface: digital_outputs1/pneumatic_gripper
    ati_sensor:
      controller_name: ft_ati_controller
      command_interface: analog_inputs/sensor_reset
      state_interfaces: 
      - analog_inputs/force_x
      - analog_inputs/force_y
      - analog_inputs/force_z
      - analog_inputs/torque_x 
      - analog_inputs/torque_y
      - analog_inputs/torque_z


