controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    delta_ctrl_word_controller:
      type: ros2_control_demo_example_10/GPIOController

    delta_moo_controller:
      type: ros2_control_demo_example_10/GPIOController

    digital_io_controller:
      type: ros2_control_demo_example_10/GPIOController

    ft_ati_controller:
      type: ros2_control_demo_example_10/GPIOController

forward_position_controller:
  ros__parameters:
    joints:
      - joint_1
    interface_name: position

forward_velocity_controller:
  ros__parameters:
    joints:
      - joint_1
    interface_name: velocity

delta_ctrl_word_controller:
  ros__parameters:
    outputs:
      - joint_1/ctrl_word
    inputs:
      - joint_1/status_word

delta_moo_controller:
  ros__parameters:
    outputs:
      - joint_1/moo
    inputs:
      - joint_1/moo_display

digital_io_controller:
  ros__parameters:
    outputs:
      - digital_outputs1/lubrication_command
      - digital_outputs1/d_output.1
      - digital_outputs1/d_output.2
      - digital_outputs1/d_output.3
      - digital_outputs1/d_output.4
      - digital_outputs1/d_output.5
      - digital_outputs1/d_output.6
      - digital_outputs1/d_output.7
      - digital_outputs2/d_output.0
      - digital_outputs2/d_output.1
      - digital_outputs2/d_output.2
      - digital_outputs2/d_output.3
      - digital_outputs2/d_output.4
      - digital_outputs2/d_output.5
      - digital_outputs2/d_output.6
      - digital_outputs2/d_output.7
    inputs:
      - digital_inputs/lubrication_state
      - digital_inputs/limit_switch_homing
      - digital_inputs/limit_switch_end
      - digital_inputs/d_input.3
      - digital_inputs/d_input.4
      - digital_inputs/d_input.5
      - digital_inputs/d_input.6
      - digital_inputs/d_input.7

ft_ati_controller:
  ros__parameters:
    outputs:
      - analog_inputs/sensor_reset
    inputs:
      - analog_inputs/sensor_channel_0
      - analog_inputs/sensor_channel_1
      - analog_inputs/sensor_channel_2
      - analog_inputs/sensor_channel_3 
      - analog_inputs/sensor_channel_4
      - analog_inputs/sensor_channel_5
      - analog_inputs/a_input_6
      - analog_inputs/a_input_7
      - analog_inputs/force_x
      - analog_inputs/force_y
      - analog_inputs/force_z
      - analog_inputs/torque_x
      - analog_inputs/torque_y
      - analog_inputs/torque_z

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
