level0_hw:
  type           : cnr/control/FakeRobotHW
  appenders      : [file, screen]
  levels         : [debug, info]
  pattern_layout : "[%5p][%d{HH:mm:ss,SSS}][%50M:%04L][%24c] %m%n"
  file_name      : level0_hw
  sampling_period: 0.002
  diagnostic_period: 0.1
  maximum_missing_cycles: 100
  feedback_joint_state_timeout: 10
  base_link: world
  tool_link: link_1
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
  kin_update_period: 0.002

  resources: [ joint_resource ]
  # joint_resource:
  joint_names:
  - joint_1
  subscribed_topics:  # name of topics sensor_msgs/JointState which contains the state of the joint handle
  - /kuka_structure/joint_states
  published_topics: # name of the topic (type sensor_msgs/JointState) that planner_hw will publish (it has to be only one)
  - /kuka_structure/joint_target
